name: docker-buildx-push

on:
  push:
    branches:
      - dev

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dev branch
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Build and publish image
        uses: zmingxie/docker_buildx@master
        with:
          dockerfile: Dockerfile
          publish: true
          imageName: rhastie/nmos-cpp
          tag: dev
          buildArg: makemt=3
          platform: linux/amd64
          dockerHubUser: ${{ secrets.DockerHub_User }}
          dockerHubPassword: ${{ secrets.DockerHub_Password }}
